# Generated by Django 3.2.25 on 2025-11-15 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LotteryDraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_number', models.CharField(max_length=50, verbose_name='期次号')),
                ('draw_date', models.DateTimeField(verbose_name='开奖时间')),
                ('winning_numbers', models.CharField(blank=True, max_length=200, verbose_name='中奖号码')),
                ('is_drawn', models.BooleanField(default=False, verbose_name='是否已开奖')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '开奖期次',
                'verbose_name_plural': '开奖期次',
            },
        ),
        migrations.CreateModel(
            name='LotteryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='彩票名称')),
                ('description', models.TextField(verbose_name='描述')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('max_number', models.IntegerField(verbose_name='最大号码')),
                ('numbers_count', models.IntegerField(verbose_name='选择号码数量')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '彩票类型',
                'verbose_name_plural': '彩票类型',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='手机号')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='账户余额')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='总消费')),
                ('total_won', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='总中奖金额')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('recharge', '充值'), ('purchase', '购买彩票'), ('winning', '中奖奖金'), ('withdraw', '提现')], max_length=20, verbose_name='交易类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('description', models.CharField(max_length=200, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='交易时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '交易记录',
                'verbose_name_plural': '交易记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LotteryTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=50, unique=True, verbose_name='彩票号码')),
                ('selected_numbers', models.CharField(max_length=200, verbose_name='选择的号码')),
                ('is_auto_select', models.BooleanField(default=False, verbose_name='是否机选')),
                ('purchase_time', models.DateTimeField(auto_now_add=True, verbose_name='购买时间')),
                ('is_winning', models.BooleanField(default=False, verbose_name='是否中奖')),
                ('winning_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='中奖金额')),
                ('is_claimed', models.BooleanField(default=False, verbose_name='是否已兑奖')),
                ('lottery_draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lottery.lotterydraw', verbose_name='开奖期次')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '彩票',
                'verbose_name_plural': '彩票',
            },
        ),
        migrations.AddField(
            model_name='lotterydraw',
            name='lottery_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lottery.lotterytype', verbose_name='彩票类型'),
        ),
        migrations.AlterUniqueTogether(
            name='lotterydraw',
            unique_together={('lottery_type', 'draw_number')},
        ),
    ]
